---
title: "alpha_diversity_3"
author: "pgfarsund"
date: "`r Sys.Date()`"
output: html_document
---

load packages

```{r}
library(here)
library(tidyverse)
library(phyloseq)
library(ggpubr)
library(janitor)
library(emmeans)
library(broom)
library(glmmTMB)
library(DHARMa)
library(performance)
library(sjPlot)

set.seed(123)
```

define function to get alpha diversity stats

```{r}
get_alpha_stats <- function(ps){
  data.frame(
  estimate_richness(ps,
    measures = c("Shannon")
  ),
  data.frame(ps@sam_data)
) |>
  dplyr::select(Shannon, phase) |>
  group_by(phase) |>
  mutate(
    ens = exp(Shannon), 
    N = vctrs::vec_count(phase)$count,
    q1_ENS = round(quantile(ens)[2], digits = 2),
    med_ENS = round(quantile(ens)[3], digits = 2),
    q3_ENS = round(quantile(ens)[4], digits = 2),
    ENS = paste0(med_ENS, " (IQR ", q3_ENS-q1_ENS, ")")
    ) |>
  dplyr::select(phase, ENS, N) |>
  distinct() |>
  arrange(phase = factor(phase, levels = c("P", "B", "M"))) |> 
  rename(Phase = phase) 
}

```

define function to write glht results to table

```{r}
# credit where it is due: https://gist.github.com/ajpelu/194e721077ec045a2b864088908e7aca
table_glht <- function(x) {
  pq <- summary(x)$test
  mtests <- cbind(pq$coefficients, pq$sigma, pq$tstat, pq$pvalues)
  error <- attr(pq$pvalues, "error")
  pname <- switch(x$alternativ, less = paste("Pr(<", ifelse(x$df ==0, "z", "t"), ")", sep = ""), 
  greater = paste("Pr(>", ifelse(x$df == 0, "z", "t"), ")", sep = ""), two.sided = paste("Pr(>|",ifelse(x$df == 0, "z", "t"), "|)", sep = ""))
  colnames(mtests) <- c("Estimate", "Std. Error", ifelse(x$df ==0, "z value", "t value"), pname)
  return(mtests)
}
```

plants

```{r}
# load phyloseq object:
plants <- readRDS(here("data/clean_data/heathland-fire-plants.RDS"))

# calculate alpha diversity measures and find medians and IQR:
(alpha_stats_plants <- get_alpha_stats(plants) |>
    mutate(Group = "Plants", .before = 1))

# test whether differences in alpha diversity are significant between phases:
data.frame(
  estimate_richness(plants,
    measures = c("Observed","Shannon")
  ),
  data.frame(plants@sam_data)
) |> 
  mutate(ENS = exp(Shannon)) -> df

### model effective number of species
plantmod <- lmerTest::lmer(ENS ~ phase + (1|blokk), data = df)
summary(plantmod)

simulateResiduals(plantmod, plot = TRUE) # looks good
testDispersion(plantmod) # looks good

# pairwise comparison
(data.frame(table_glht(glht(plantmod, linfct = mcp(phase = "Tukey")))) |> 
  rownames_to_column("Comparison") |> 
  mutate(across(where(is.numeric), round, 3), 
         Group = "Plants", .before = 1, 
         Comparison = sub("M - B", "B - M", Comparison)) |> 
  rename("Std.error" = "Std..Error", 
         "Z-value" = "z.value",
         "P-value" = "Pr...z..") |> 
  arrange(match(Comparison, c("P - B", "P - M", "B - M"))) -> plantpair)

# make boxplots to go with the model results
(df |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = ENS,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic(base_size = 17) +
  geom_boxplot(linewidth = 0.6, alpha = 0.75, outlier.shape = NA, width = 0.5) +
  geom_jitter(
    size = 2, shape = 21, stroke = 1, alpha = 0.8,
    position = position_jitter(height = 0, width = 0.3)
  ) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank()
    ) +
  scale_fill_brewer(palette = "Greens") +
  scale_color_manual(values = rep("black", times = length(unique(plants@sam_data$phase)))) +
  ylab(" ") +
  ggtitle("Plants") +
  geom_segment(
    x = 1, xend = 2,
    y = 19, yend = 19
  ) +
  annotate(
    geom = "text", label = ".", size = 12,
    x = 1.5, y = 21
  ) -> plantplot)

```

malaise traps

```{r}
# load and normalise phyloseq object:
malaise <- readRDS(here("data/clean_data/heathland-fire-malaise.RDS"))
malaise <- prune_taxa(taxa_sums(malaise) > 0, malaise)

malrar <- rarefy_even_depth(malaise,
  rngseed = 123,
  replace = F,
  trimOTUs = T,
  sample.size = min(sample_sums(malaise))
)

# calculate alpha diversity measures and find medians and IQR:
alpha_stats_malaise <- get_alpha_stats(malrar) |>
    mutate(Group = "Malaise traps", .before = 1)

# test whether differences in alpha diversity are significant between phases:
data.frame(
  estimate_richness(malrar,
    measures = c("Shannon")
  ),
  data.frame(malrar@sam_data)
) |> 
  mutate(ENS = exp(Shannon)) -> df

# make boxplots
(df |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = ENS,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic(base_size = 17) +
  geom_point(size = 3, shape = 21, stroke = 1, alpha = 0.8) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank()) +
  scale_fill_manual(values = c("#FDE0EF", "#DE77AE", "#C51B7D")) +
  scale_color_manual(values = rep("black", times = length(unique(malrar@sam_data$phase)))) +
  ylab(" ") +
  ggtitle("Malaise traps") -> inrich)


```

pitfall traps

```{r}
# load and normalise phyloseq object:
pit <- readRDS(here("data/clean_data/heathland-fire-pitfall.RDS"))

pitrar <- rarefy_even_depth(pit,
  rngseed = 123,
  replace = F,
  trimOTUs = T,
  sample.size = 10
)

# calculate alpha diversity measures and find medians and IQR:
alpha_stats_pitfall <- get_alpha_stats(pitrar) |>
    mutate(Group = "Pitfall traps", .before = 1)

# test whether differences in alpha diversity are significant between phases:
(data.frame(
  estimate_richness(pitrar,
    measures = c("Observed", "Shannon")
  ),
  data.frame(pitrar@sam_data)
) |> 
  mutate(ENS = exp(Shannon), 
         sub_blokk = paste0(blokk, "_", sub_block)) -> df)

### model effective number of species
pitmod <- lmerTest::lmer(ENS ~ phase + (1|blokk) + (1|sub_block), data = df)
summary(pitmod)

simulateResiduals(pitmod, plot = TRUE) # looks good
testDispersion(pitmod) # looks good

# pairwise comparison
(data.frame(table_glht(glht(pitmod, linfct = mcp(phase = "Tukey")))) |> 
  rownames_to_column("Comparison") |> 
  mutate(across(where(is.numeric), round, 3), 
         Group = "Pitfall traps", .before = 1, 
         Comparison = sub("M - B", "B - M", Comparison)) |> 
  rename("Std.error" = "Std..Error", 
         "Z-value" = "z.value",
         "P-value" = "Pr...z..") |> 
  arrange(match(Comparison, c("P - B", "P - M", "B - M"))) -> pitpair)

# make boxplots to go with model results
(df |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = ENS,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic(base_size = 17) +
  geom_boxplot(linewidth = 0.6, alpha = 0.75, outlier.shape = NA, width = 0.5) +
  geom_jitter(
    size = 2, shape = 21, stroke = 1, alpha = 0.8,
    position = position_jitter(height = 0, width = 0.3)
  ) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank()
    ) +
  scale_fill_manual(values = c("tan", "tan3", "tan4")) +
  scale_color_manual(values = rep("black", times = length(unique(pitrar@sam_data$phase)))) +
  ylab(" ") +
  ggtitle("Pitfall traps") -> pitrich)

```

nematodes

```{r}
# load and normalise phyloseq object:
nematodes <- readRDS(here("data/clean_data/heathland-fire-nematodes.RDS"))

nemrar <- rarefy_even_depth(nematodes,
  rngseed = 123,
  replace = F,
  trimOTUs = T,
  sample.size = min(sample_sums(nematodes))
)

# calculate alpha diversity measures and find medians and IQR:
alpha_stats_nematodes <- get_alpha_stats(nemrar) |>
    mutate(Group = "Nematodes", .before = 1)

# test whether differences in alpha diversity are significant between phases:
(data.frame(
  estimate_richness(nemrar,
    measures = c("Observed", "Shannon")
  ),
  data.frame(nemrar@sam_data)
) |> 
  rename(Richness = Observed) |> 
  mutate(blokk = sapply(strsplit(Navn, split = '_', fixed = TRUE), `[`, 1), 
         ENS = exp(Shannon)) -> df)

### model effective number of species
nemmod <- lmerTest::lmer(ENS ~ phase + (1|blokk) + (1|month), data = df)
summary(nemmod)

simulateResiduals(nemmod, plot = TRUE) # looks good
testDispersion(nemmod) # looks good

# pairwise comparison
(data.frame(table_glht(glht(nemmod, linfct = mcp(phase = "Tukey")))) |> 
  rownames_to_column("Comparison") |> 
  mutate(across(where(is.numeric), round, 3), 
         Group = "Nematodes", .before = 1, 
         Comparison = sub("M - B", "B - M", Comparison)) |> 
  rename("Std.error" = "Std..Error", 
         "Z-value" = "z.value",
         "P-value" = "Pr...z..") |> 
  arrange(match(Comparison, c("P - B", "P - M", "B - M"))) -> nempair)

# make boxlots to go with the model results
(df |>
  mutate(
    phase = sub("Pioner", "P", phase),
    phase = sub("Bygg", "B", phase),
    phase = sub("Moden", "M", phase)
  ) |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = ENS,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic(base_size = 17) +
  geom_boxplot(linewidth = 0.6, alpha = 0.75, outlier.shape = NA, width = 0.5) +
  geom_jitter(
    size = 2, shape = 21, stroke = 1, alpha = 0.8,
    position = position_jitter(height = 0, width = 0.3)
  ) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank()
    ) +
  scale_fill_manual(values = c("#F7FBFF", "#9ECAE1", "#08519C")) +
  scale_color_manual(values = rep("black", times = length(unique(nemrar@sam_data$phase)))) +
  ylab(" ") +
  ggtitle("Nematodes") +
  geom_segment(
    x = 2, xend = 3,
    y = 10, yend = 10
  ) +
  annotate(
    geom = "text", label = "***", size = 10,
    x = 2.5, y = 10.1
  ) +
  geom_segment(
    x = 1, xend = 3,
    y = 11, yend = 11
  ) +
  annotate(
    geom = "text", label = ".", size = 10,
    x = 2, y = 12
  ) +
  geom_segment(
    x = 1, xend = 2,
    y = 12, yend = 12
  ) +
  annotate(
    geom = "text", label = "**", size = 10,
    x = 1.5, y = 12.1
  ) +
  coord_cartesian(ylim = c(2.5, 13))  -> nemrich)


```

fungi 

```{r}
# load and normalise phyloseq object:
fungi <- readRDS(here("data/clean_data/heathland-fire-fungi.RDS"))
fungi <- prune_taxa(taxa_sums(fungi) > 0, fungi)

(funrar <- rarefy_even_depth(fungi,
  rngseed = 123,
  replace = F,
  trimOTUs = T,
  sample.size = min(sample_sums(fungi))
))

# calculate alpha diversity measures and find medians and IQR:
(alpha_stats_fungi <- get_alpha_stats(funrar) |>
    mutate(Group = "Fungi", .before = 1))

# test whether differences in alpha diversity are significant between phases:
data.frame(
  estimate_richness(funrar,
    measures = c("Observed", "Shannon")
  ),
  data.frame(funrar@sam_data)
) |> 
  rename(Richness = Observed) |>
  mutate(blokk = sapply(strsplit(Navn, split = '_', fixed = TRUE), `[`, 1), 
         ENS = exp(Shannon)) -> df

### model effective number of species
funmod <- lmerTest::lmer(ENS ~ phase + (1|blokk) + (1|month), data = df)
summary(funmod)
isSingular(funmod)

# the fungal model is a singular fit. this could symptom of our random effects having few levels or that the model is simply overfitted. from the output of summary(mod) we see that "month" explains no variance in the data. to get past this issue, we fit a Bayesian LMM with package blme and apply a Gamma prior as recommended in Chung et al. 2013 (https://doi.org/10.1007/s11336-013-9328-2). 

library(blme)

funmodblme <- blme::blmer(ENS ~ phase + (1|blokk) + (1|month), data = df, 
                          cov.prior = gamma(2.5, 1))
summary(funmodblme)
simulateResiduals(funmodblme, plot = TRUE) # looks good
#testDispersion(funmodblme) # not supported

# pairwise comparison
(data.frame(table_glht(glht(funmodblme, linfct = mcp(phase = "Tukey")))) |> 
  rownames_to_column("Comparison") |> 
  mutate(across(where(is.numeric), round, 3), 
         Group = "Fungi", .before = 1, 
         Comparison = sub("M - B", "B - M", Comparison)) |> 
  rename("Std.error" = "Std..Error", 
         "Z-value" = "z.value",
         "P-value" = "Pr...z..") |> 
  arrange(match(Comparison, c("P - B", "P - M", "B - M"))) -> funpair)

(df |>
  mutate(
    phase = sub("Pioner", "P", phase),
    phase = sub("Bygg", "B", phase),
    phase = sub("Moden", "M", phase)
  ) |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = ENS,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic(base_size = 17) +
  geom_boxplot(linewidth = 0.6, alpha = 0.75, outlier.shape = NA, width = 0.5) +
  geom_jitter(
    size = 2, shape = 21, stroke = 1, alpha = 0.8,
    position = position_jitter(height = 0, width = 0.3)
  ) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank()) +
  scale_fill_manual(values = c("#DADAEB", "#9E9AC8", "#54278F")) +
  scale_color_manual(values = rep("black", times = length(unique(funrar@sam_data$phase)))) +
  ylab(" ") +
  ggtitle("Fungi") -> funrich)

```

bacteria

```{r}
# load and normalise phyloseq object:
bacteria <- readRDS(here("data/clean_data/heathland-fire-bacteria.RDS"))

bacrar <- rarefy_even_depth(bacteria,
  rngseed = 123,
  replace = F,
  trimOTUs = T,
  sample.size = 18963
)

# calculate alpha diversity measures and find medians and IQR:
(alpha_stats_bacteria <- get_alpha_stats(bacrar) |>
    mutate(Group = "Bacteria", .before = 1))

# test whether differences in alpha diversity are significant between phases:
data.frame(
  estimate_richness(bacrar,
    measures = c("Observed", "Shannon")
  ),
  data.frame(bacrar@sam_data)
) |> 
  rename(Richness = Observed) |> 
  mutate(blokk = sapply(strsplit(Navn, split = '_', fixed = TRUE), `[`, 1), 
         ENS = exp(Shannon)) -> df

### model effective number of species
bacmod <- lmerTest::lmer(ENS ~ phase + (1|blokk) + (1|month), data = df)
summary(bacmod)

simulateResiduals(bacmod, plot = TRUE) # looks good
testDispersion(bacmod) # looks good

# pairwise comparison
(data.frame(table_glht(glht(bacmod, linfct = mcp(phase = "Tukey")))) |> 
  rownames_to_column("Comparison") |> 
  mutate(across(where(is.numeric), round, 3), 
         Group = "Bacteria", .before = 1, 
         Comparison = sub("M - B", "B - M", Comparison)) |> 
  rename("Std.error" = "Std..Error", 
         "Z-value" = "z.value",
         "P-value" = "Pr...z..") |> 
  arrange(match(Comparison, c("P - B", "P - M", "B - M"))) -> bacpair)

(df |>
  mutate(
    phase = sub("Pioner", "P", phase),
    phase = sub("Bygg", "B", phase),
    phase = sub("Moden", "M", phase)
  ) |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = ENS,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic(base_size = 17) +
  geom_boxplot(linewidth = 0.6, alpha = 0.75, outlier.shape = NA, width = 0.5) +
  geom_jitter(
    size = 2, shape = 21, stroke = 1, alpha = 0.8,
    position = position_jitter(height = 0, width = 0.3)
  ) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank()) +
  scale_fill_manual(values = c("#FEE0D2", "#FC9272", "#CB181D")) +
  scale_color_manual(values = rep("black", times = length(unique(funrar@sam_data$phase)))) +
  ylab(" ") +
  ggtitle("Bacteria") -> bacrich)

```

get diversity stats

```{r}
# make a data frame from all ENS stats
(rbind(
  alpha_stats_plants, 
  alpha_stats_malaise, 
  alpha_stats_pitfall, 
  alpha_stats_nematodes, 
  alpha_stats_fungi, 
  alpha_stats_bacteria
) -> ens)
```

print LMM outputs

```{r}
rbind(
  data.frame(Group = "Plants", 
             broom.mixed::tidy(plantmod)),
  data.frame(Group = "Pitfall traps", 
             broom.mixed::tidy(pitmod)),
  data.frame(Group = "Nematodes", 
             broom.mixed::tidy(nemmod)),
  data.frame(Group = "Fungi", 
             broom.mixed::tidy(funmod)),
  data.frame(Group = "Bacteria", 
             broom.mixed::tidy(bacmod))
) |> 
  rename("random_effect" = group) -> lmm.output
writexl::write_xlsx(lmm.output, "~/Desktop/lmmoutput.xlsx")
```

print pairwise comparisons

```{r}
rbind(
  plantpair, 
  pitpair, 
  nempair, 
  funpair, 
  bacpair
) -> lmm.pairwise 
writexl::write_xlsx(lmm.pairwise, "~/Desktop/pairwise.xlsx")
```


combine boxplots 

```{r}
fig <- ggarrange(plantplot, inrich, pitrich, 
                 nemrich, funrich, bacrich, nrow = 2, ncol = 3) # pdf 3 x 11.69
fig <- annotate_figure(fig,
                bottom = text_grob("Successional phase", color = "black", size = 16),
                left = text_grob("Effective number of species", color = "black", rot = 90, size = 16))
fig
```


