---
title: "ordination_and_permanova"
author: "pgfarsund"
date: "`r Sys.Date()`"
output: html_document
---

load required packages

```{r}
library(here)
library(tidyverse)
library(BiodiversityR)
library(ggforce)
library(phyloseq)
library(ggpubr)

set.seed(123)
```

define function to plot ordination with ggplot2

```{r}
get_ordination_plot <- function(ps, ordidata, cols, tit){
ggplot() +
  theme_classic() +
  geom_vline(xintercept = c(0), color = "grey10", linetype = 2) +
  geom_hline(yintercept = c(0), color = "grey10", linetype = 2) +
  xlab("NMDS1") +
  ylab("NMDS2") +
  scale_x_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  scale_y_continuous(sec.axis = dup_axis(labels = NULL, name = NULL)) +
  geom_point(
    data = ordidata,
    aes(
      x = axis1, y = axis2,
      colour = factor(ps@sam_data$phase, levels = c("P", "B", "M")),
      fill = factor(ps@sam_data$phase, levels = c("P", "B", "M"))
    ),
    pch = 21, size = 4, alpha = 0.8
  ) +
  geom_point(
    data = centroids.long(ordidata,
      FUN = mean,
      grouping = factor(ps@sam_data$phase, levels = c("P", "B", "M")),
      centroids.only = TRUE
    ),
    aes(x = axis1c, y = axis2c, colour = Centroid, fill = Centroid),
    pch = 24, size = 4, alpha = 1
  ) +
  scale_color_manual(values = rep("black", times = 12)) +
  scale_shape_manual(values = c(21, 22)) +
  scale_fill_manual(values = cols) +
  labs(title = tit) +
  theme(
    legend.title = element_blank(),
    legend.position = "bottom") +
    geom_mark_hull(data=ordidata, 
                   aes(x=axis1, y=axis2, fill=phase, 
                       fill=after_scale(alpha(fill, 0.2))), 
                   concavity=0.1, size=0.2, show.legend=FALSE)
}
```

plants

```{r}
set.seed(123)

# load phyloseq object:
plants <- readRDS(here("data/clean_data/heathland-fire-plants.RDS"))

plants <- transform_sample_counts(plants, function(x) x / sum(x)) # compute relative abundances

ordmod <- metaMDS(comm = decostand(plants@otu_table, method = "hellinger"), 
                  distance = "bray", k = 2)

sites.long <- sites.long(ordiplot(ordmod, choices = c(1, 2)), 
                          env.data = plants@sam_data)

get_ordination_plot(ps = plants, ordidata = sites.long, 
                    cols = c("#C7E9C0", "#41AB5D", "#00441B"), tit = "Plants") -> plantord

# perform permanova
adonis2(decostand(plants@otu_table, method = "hellinger") ~ phase,
  data = data.frame(plants@sam_data),
  permutations = 9999,
  method = "bray"
) -> plantperm

# perform pairwise permanova
pairwise.adonis2(mat ~ phase,
  data = data.frame(plants@sam_data),
  nperm = 9999,
  method = "bray"
) -> plantpairperm

```

malaise traps

```{r}
malaise <- readRDS(here("data/clean_data/heathland-fire-malaise.RDS"))
malaise <- prune_taxa(taxa_sums(malaise) > 0, malaise)

malrar <- rarefy_even_depth(malaise,
  rngseed = 123,
  replace = F,
  trimOTUs = T,
  sample.size = min(sample_sums(malaise))
)

ordmod <- metaMDS(comm = decostand(t(malrar@otu_table), method = "hellinger"), 
                  distance = "bray", k = 2)

sites.long <- sites.long(ordiplot(ordmod, choices = c(1, 2)), 
                          env.data = malrar@sam_data)

get_ordination_plot(ps = malrar, ordidata = sites.long, 
                    cols = c("#DE77AE", "#C51B7D", "#FDE0EF"), tit = "Malaise traps") -> malord

```

pitfall traps

```{r}
set.seed(123)
pit <- readRDS(here("data/clean_data/heathland-fire-pitfall.RDS"))

pitrar <- rarefy_even_depth(pit,
  rngseed = 123,
  replace = F,
  trimOTUs = T,
  sample.size = 10
)

ordmod <- metaMDS(comm = decostand(pitrar@otu_table, method = "hellinger"), 
                  distance = "bray", k = 2, autotransform = T)

sites.long <- sites.long(ordiplot(ordmod, choices = c(1, 2)), 
                          env.data = pitrar@sam_data)

get_ordination_plot(ps = pitrar, ordidata = sites.long, 
                    cols = c("tan", "tan3", "tan4"), tit = "Pitfall traps") -> pitord

adonis2(decostand(pitrar@otu_table, method = "hellinger") ~ phase,
  data = data.frame(pitrar@sam_data),
  permutations = 9999,
  method = "bray"
) -> pitperm

pairwise.adonis2(decostand(pitrar@otu_table, method = "hellinger") ~ phase,
  data = data.frame(pitrar@sam_data),
  nperm = 9999,
  method = "bray"
) -> pitpairperm
```

nematodes

```{r}
set.seed(123)
# load and normalise phyloseq object:
nematodes <- readRDS(here("data/clean_data/heathland-fire-nematodes.RDS"))
nematodes <- prune_taxa(taxa_sums(nematodes) > 0, nematodes)

nemrar <- rarefy_even_depth(nematodes,
  rngseed = 123,
  replace = F,
  trimOTUs = T,
  sample.size = min(sample_sums(nematodes))
)

ordmod <- metaMDS(comm = decostand(nemrar@otu_table, method = "hellinger"), 
                  distance = "bray", k = 2, autotransform = T)

sites.long <- sites.long(ordiplot(ordmod, choices = c(1, 2)), 
                          env.data = nemrar@sam_data)

get_ordination_plot(ps = nemrar, ordidata = sites.long, 
                    cols = c("#F7FBFF", "#9ECAE1", "#08519C"), tit = "Nematodes") -> nemord

adonis2(decostand(nemrar@otu_table, method = "hellinger") ~ phase,
  data = data.frame(nemrar@sam_data),
  permutations = 9999, method = "bray"
) -> nemperm

pairwise.adonis2(decostand(nemrar@otu_table, method = "hellinger") ~ phase,
  data = data.frame(nemrar@sam_data),
  nperm = 9999, method = "bray"
) -> nemparperm

```

fungi

```{r}
# load and normalise phyloseq object:
fungi <- readRDS(here("data/clean_data/heathland-fire-fungi.RDS"))

funrar <- rarefy_even_depth(fungi,
  rngseed = 123,
  replace = F,
  trimOTUs = T,
  sample.size = min(sample_sums(fungi))
)

ordmod <- metaMDS(comm = decostand(funrar@otu_table, method = "hellinger"), 
                  distance = "bray", k = 2, autotransform = T)

sites.long <- sites.long(ordiplot(ordmod, choices = c(1, 2)), 
                          env.data = funrar@sam_data)

get_ordination_plot(ps = nemrar, ordidata = sites.long, 
                    cols = c("#DADAEB", "#9E9AC8", "#54278F"), tit = "Fungi") -> funord

adonis2(decostand(funrar@otu_table, method = "hellinger") ~ phase,
  data = data.frame(funrar@sam_data),
  nperm = 9999, method = "bray"
) -> funperm

pairwise.adonis2(decostand(funrar@otu_table, method = "hellinger") ~ phase,
  data = data.frame(funrar@sam_data),
  nperm = 9999, method = "bray"
) -> funparperm

```

bacteria

```{r}
# load and normalise phyloseq object:
bacteria <- readRDS(here("data/clean_data/heathland-fire-bacteria.RDS"))

bacrar <- rarefy_even_depth(bacteria,
  rngseed = 123,
  replace = F,
  trimOTUs = T,
  sample.size = 18963
)

ordmod <- metaMDS(comm = decostand(bacrar@otu_table, method = "hellinger"), 
                  distance = "bray", k = 2, autotransform = T)

sites.long <- sites.long(ordiplot(ordmod, choices = c(1, 2)), 
                          env.data = bacrar@sam_data)

get_ordination_plot(ps = bacrar, ordidata = sites.long, 
                    cols = c("#FC9272", "#CB181D", "#FEE0D2"), tit = "Bacteria") -> bacord

adonis2(decostand(bacrar@otu_table, method = "hellinger") ~ phase,
  data = data.frame(bacrar@sam_data),
  nperm = 9999, method = "bray"
) -> bacperm

pairwise.adonis2(decostand(bacrar@otu_table, method = "hellinger") ~ phase,
  data = data.frame(bacrar@sam_data),
  nperm = 9999, method = "bray"
) -> bacparperm

```

combine ordination plots into Supplementary figure S2

```{r}
ggarrange(plantord, malord, pitord, 
          nemord, funord, bacord, 
          nrow = 2, ncol = 3) # 1300 x 800
```

combine permanova results into Supplementary table 4

```{r}
rbind(
  data.frame(group = "Plants", 
             plantperm),
  data.frame(group = "Pitfall traps", 
             pitperm),
  data.frame(group = "Nematodes", 
             nemperm),
  data.frame(group = "Fungi", 
             funperm),
  data.frame(group = "Bacteria", 
             bacperm)
) |>
  rownames_to_column(var = "mod_resid") |> 
  relocate(mod_resid, .after = 2) -> permanova.output
writexl::write_xlsx(permanova.output, "~/Desktop/perm.xlsx")
```

combine pairwise permanova into Supplementary table 5

```{r}
rbind(data.frame(group = "Plants", 
                 comparison = "B_vs_P", 
                 plantpairperm$B_vs_P), 
      data.frame(group = "Plants", 
                 comparison = "B_vs_M", 
                 plantpairperm$B_vs_M), 
      data.frame(group = "Plants", 
                 comparison = "M_vs_P", 
                 plantpairperm$M_vs_P), 
      data.frame(group = "Pitfall traps", 
                 comparison = "B_vs_P", 
                 pitpairperm$B_vs_P), 
      data.frame(group = "Pitfall traps", 
                 comparison = "B_vs_M", 
                 pitpairperm$B_vs_M), 
      data.frame(group = "Pitfall traps", 
                 comparison = "M_vs_P", 
                 pitpairperm$M_vs_P), 
      data.frame(group = "Nematodes", 
                 comparison = "B_vs_P", 
                 nemparperm$B_vs_P), 
      data.frame(group = "Nematodes", 
                 comparison = "B_vs_M", 
                 nemparperm$B_vs_M), 
      data.frame(group = "Nematodes", 
                 comparison = "M_vs_P", 
                 nemparperm$M_vs_P),
      data.frame(group = "Fungi", 
                 comparison = "B_vs_P", 
                 funparperm$B_vs_P), 
      data.frame(group = "Fungi", 
                 comparison = "B_vs_M", 
                 funparperm$B_vs_M), 
      data.frame(group = "Fungi", 
                 comparison = "M_vs_P", 
                 funparperm$M_vs_P), 
      data.frame(group = "Bacteria", 
                 comparison = "P_vs_B", 
                 bacparperm$P_vs_B), 
      data.frame(group = "Bacteria", 
                 comparison = "M_vs_B", 
                 bacparperm$M_vs_B), 
      data.frame(group = "Bacteria", 
                 comparison = "M_vs_P", 
                 bacparperm$M_vs_P)) |>
  rownames_to_column(var = "mod_resid") |> 
  relocate(mod_resid, .after = 2) -> pairpermanova.output
writexl::write_xlsx(pairpermanova.output, "~/Desktop/pairperm.xlsx")
```

