---
title: "alpha_diversity_2.0"
author: "pgfarsund"
date: "`r Sys.Date()`"
output: html_document
---

load packages

```{r}
library(here)
library(tidyverse)
library(phyloseq)
library(ggpubr)
library(janitor)
library(emmeans)
library(broom)
library(glmmTMB)
library(DHARMa)
library(performance)
library(sjPlot)

set.seed(123)
```

define function to get alpha diversity stats

```{r}
get_alpha_stats <- function(ps){
  data.frame(
  estimate_richness(ps,
    measures = c("Richness", "Shannon")
  ),
  data.frame(ps@sam_data)
) |>
  select(Richness, Shannon, phase) |>
  group_by(phase) |>
  mutate(
    N = vctrs::vec_count(phase)$count,
    q1_richness = quantile(Richness)[2],
    med_richness = quantile(Richness)[3],
    q3_richness = quantile(Richness)[4],
    q1_shannon = quantile(Shannon)[2],
    med_shannon = quantile(Shannon)[3],
    q3_shannon = quantile(Shannon)[4],
    richness = paste0(med_richness, " (IQR ", round(q3_richness-q1_richness, digits = 2), ")"), 
    shannon = paste0(round(med_shannon, digits = 2), " (IQR ", round(q3_shannon-q1_shannon, digits = 2), ")")
  ) |>
  select(phase, richness, shannon, N) |>
  distinct() |>
  arrange(phase = factor(phase, levels = c("P", "B", "M")))
}

```

plants

```{r}
# load phyloseq object:
plants <- readRDS(here("data/clean_data/heathland-fire-plants.RDS"))

# calculate alpha diversity measures and find medians and IQR:
(alpha_stats_plants <- get_alpha_stats(plants) |>
    mutate(group = "Plants", .before = 1))

# test whether differences in alpha diversity are significant between phases:
data.frame(
  estimate_richness(plants,
    measures = c("Observed", "Shannon")
  ),
  data.frame(plants@sam_data)
) |> 
  rename(Richness = Observed)  -> df

### RICHNESS
plantrichmod <- glmmTMB(Richness ~ phase + (1|blokk/plott), 
               data = df, family = genpois(link = "log")) # fit model
summary(plantrichmod)

simulateResiduals(plantrichmod, plot = TRUE) # looks good
testDispersion(plantrichmod) # looks good

check_convergence(plantrichmod) # model converges
check_singularity(plantrichmod) # model is a singular fit

# the singular fit is likely a symptom of our random "blokk" effect having few levels. from the output of summary(mod) we see that the random effect of "blokk" explains <0.000 percent of the variance in the data. to get past this issue, we apply a Gamma prior as recommended in Chung et al. 2013 (https://doi.org/10.1007/s11336-013-9328-2)

plantrichmodup <- update(plantrichmod, 
                       priors = data.frame(prior = "gamma(1, 2.5)",  
                                           class = "ranef"))

check_singularity(plantrichmodup) # the model is no longer a singular fit
simulateResiduals(plantrichmodup, plot = TRUE) # looks good
testDispersion(plantrichmodup) # looks good
summary(plantrichmodup)

sjPlot::tab_model(plantrichmodup, use.viewer = TRUE, string.est = "Estimate", show.ci = 0.95)
confint(plantrichmodup)

# do a pairwise comparison with emmeans
(plantrichmodpair <- data.frame(emmeans(plantrichmodup, specs = pairwise ~ phase)$contrast) |> 
  mutate(group = "Plants", .before = 1) |>
  mutate(p.value = round(p.value, digits = 5)))

### SHANNON
plantshamod <- glmmTMB(Shannon ~ phase + (1|blokk), 
               data = df, family = gaussian(link = "identity"))
summary(plantshamod)
simulateResiduals(plantshamod, plot = TRUE) # looks good
testDispersion(plantshamod) # looks good


# do a pairwise comparison with emmeans
(plantshamod <- data.frame(emmeans(plantshamod, specs = pairwise ~ phase)$contrast) |> 
  mutate(group = "Plants", .before = 1))

# make boxplots to go with the model results
(df |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = Richness,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic(base_size = 12) +
  geom_boxplot(linewidth = 0.6, alpha = 1, outlier.shape = NA, width = 0.5) +
  geom_jitter(
    size = 2, shape = 21, stroke = 1, alpha = 0.5,
    position = position_jitter(height = 0, width = 0.3)
  ) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.text.x = element_text(color = "white"),
    axis.ticks.x = element_blank()
  ) +
  scale_fill_brewer(palette = "Greens") +
  scale_color_manual(values = rep("black", times = length(unique(plants@sam_data$phase)))) +
  ylab("Richness") +
  ggtitle("Plants") +
  geom_segment(
    x = 1, xend = 2,
    y = 25, yend = 25
  ) +
  annotate(
    geom = "text", label = "***", size = 12,
    x = 1.5, y = 25.5
  ) +
  geom_segment(
    x = 1, xend = 3,
    y = 23, yend = 23
  ) +
  annotate(
    geom = "text", label = "**", size = 12,
    x = 2, y = 23.5
  ) +
  coord_cartesian(ylim = c(9, 27)) -> plarich)

(df |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = Shannon,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic(base_size = 12) +
  geom_boxplot(linewidth = 0.6, alpha = 1, outlier.shape = NA, width = 0.5) +
  geom_jitter(
    size = 2, shape = 21, stroke = 1, alpha = 0.5,
    position = position_jitter(height = 0, width = 0.3)
  ) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank()
  ) +
  scale_fill_brewer(palette = "Greens") +
  scale_color_manual(values = rep("black", times = length(unique(plants@sam_data$phase)))) +
  ylab("Shannon") +
  ggtitle(" ") +
  geom_segment(
    x = 1, xend = 2,
    y = 3, yend = 3
  ) +
  annotate(
    geom = "text", label = "*", size = 12,
    x = 1.5, y = 3.05
  ) +
  coord_cartesian(ylim = c(1.5, 3.4)) -> plasha)
```

malaise traps

```{r}
# load and normalise phyloseq object:
malaise <- readRDS(here("data/clean_data/heathland-fire-malaise.RDS"))
malaise <- prune_taxa(taxa_sums(malaise) > 0, malaise)

malrar <- rarefy_even_depth(malaise,
  rngseed = 123,
  replace = F,
  trimOTUs = T,
  sample.size = min(sample_sums(malaise))
)

# calculate alpha diversity measures and find medians and IQR:
alpha_stats_malaise <- get_alpha_stats(malrar) |>
    mutate(group = "Malaise traps", .before = 1)

# test whether differences in alpha diversity are significant between phases:
data.frame(
  estimate_richness(malrar,
    measures = c("Observed", "Shannon")
  ),
  data.frame(malrar@sam_data)
) |> 
  rename(Richness = Observed) -> df

# make boxplots
(df |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = Richness,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic() +
  geom_point(size = 2, shape = 21, stroke = 1, alpha = 0.8) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.text.x = element_text(color = "white"),
    axis.ticks.x = element_blank()
  ) +
  scale_fill_manual(values = c("#FDE0EF", "#DE77AE", "#C51B7D")) +
  scale_color_manual(values = rep("black", times = length(unique(malrar@sam_data$phase)))) +
  ylab(" ") +
  ggtitle("Malaise traps") -> inrich)

(df |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = Shannon,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic() +
  geom_point(size = 2, shape = 21, stroke = 1, alpha = 0.8) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank(),
    plot.title = element_text(color = "white")
  ) +
  scale_fill_manual(values = c("#FDE0EF", "#DE77AE", "#C51B7D")) +
  scale_color_manual(values = rep("black", times = length(unique(malrar@sam_data$phase)))) +
  ylab(" ") +
  ggtitle(" e") -> insha)

(ggarrange(inrich, insha, nrow = 2) -> malaise_alphaplot)
```

pitfall traps

```{r}
# load and normalise phyloseq object:
pit <- readRDS(here("data/clean_data/heathland-fire-pitfall.RDS"))

pitrar <- rarefy_even_depth(pit,
  rngseed = 123,
  replace = F,
  trimOTUs = T,
  sample.size = 10
)

# calculate alpha diversity measures and find medians and IQR:
alpha_stats_pitfall <- get_alpha_stats(pitrar) |>
    mutate(group = "Pitfall traps", .before = 1)

# test whether differences in alpha diversity are significant between phases:
(data.frame(
  estimate_richness(pitrar,
    measures = c("Observed", "Shannon")
  ),
  data.frame(pitrar@sam_data)
) |> 
  rename(Richness = Observed) -> df)

### RICHNESS
pitrichmod <- glmmTMB(Richness ~ phase + (1|blokk/sub_block), 
               data = df, family = poisson(link = "log")) # fit model
summary(pitrichmod) # variance from random effects is very low, check for singularity
check_singularity(pitrichmod) # singular fit

pitrichmodup <- update(pitrichmod, 
                       priors = data.frame(prior = "gamma(1, 2.5)",  
                                           class = "ranef"))

check_singularity(pitrichmodup) # the model is no longer a singular fit
simulateResiduals(pitrichmodup, plot = TRUE) # looks ok, no significant qq plot residuals
testDispersion(pitrichmodup) # looks ok - not entirely underdispersed
summary(pitrichmodup)

(pitrichmodpair <- data.frame(emmeans(pitrichmodup, specs = pairwise ~ phase)$contrast) |> 
  mutate(group = "Pitfall traps", .before = 1))

### SHANNON
pitshamod <- glmmTMB(Shannon ~ phase + (1|blokk/sub_block), 
               data = df, family = gaussian(link = "logit")) # fit model
summary(pitshamod) # variance from random effects is very low, check for singularity
simulateResiduals(pitshamod, plot = TRUE) # looks ok, 
testDispersion(pitshamod) # looks good
summary(pitshamod)

(pitshamod <- data.frame(emmeans(pitshamod, specs = pairwise ~ phase)$contrast) |> 
  mutate(group = "Pitfall traps", .before = 1))

# make boxplots to go with model results
(df |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = Richness,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic() +
  geom_boxplot(linewidth = 0.6, alpha = 1, outlier.shape = NA, width = 0.5) +
  geom_jitter(
    size = 2, shape = 21, stroke = 1, alpha = 0.5,
    position = position_jitter(height = 0, width = 0.3)
  ) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.text.x = element_text(color = "white"),
    axis.ticks.x = element_blank()
  ) +
  scale_fill_manual(values = c("tan", "tan3", "tan4")) +
  scale_color_manual(values = rep("black", times = length(unique(pitrar@sam_data$phase)))) +
  ylab(" ") +
  ggtitle("Pitfall traps") -> pitrich)

(df |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = Shannon,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic() +
  geom_boxplot(linewidth = 0.6, alpha = 1, outlier.shape = NA, width = 0.5) +
  geom_jitter(
    size = 2, shape = 21, stroke = 1, alpha = 0.5,
    position = position_jitter(height = 0, width = 0.3)
  ) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank()
  ) +
  scale_fill_manual(values = c("tan", "tan3", "tan4")) +
  scale_color_manual(values = rep("black", times = length(unique(pitrar@sam_data$phase)))) +
  ylab(" ") +
  ggtitle(" ") -> pitsha)

```

nematodes

```{r}
# load and normalise phyloseq object:
nematodes <- readRDS(here("data/clean_data/heathland-fire-nematodes.RDS"))

nemrar <- rarefy_even_depth(nematodes,
  rngseed = 123,
  replace = F,
  trimOTUs = T,
  sample.size = min(sample_sums(nematodes))
)

# calculate alpha diversity measures and find medians and IQR:
alpha_stats_nematodes <- get_alpha_stats(nemrar) |>
    mutate(group = "Nematodes", .before = 1)

# test whether differences in alpha diversity are significant between phases:
data.frame(
  estimate_richness(nemrar,
    measures = c("Richness", "Shannon")
  ),
  data.frame(nemrar@sam_data)
) |> 
  mutate(blokk = sapply(strsplit(Navn, split = '_', fixed = TRUE), `[`, 1)) -> df

### RICHNESS
nemrichmod <- glmmTMB(Richness ~ phase + (1|blokk) + (1|month), 
               data = df, family = genpois(link = "log")) # fit model
summary(nemrichmod)

simulateResiduals(nemrichmod, plot = TRUE) # looks ok, nothing significant in the qq plot residuals
testDispersion(nemrichmod) # looks good
check_singularity(nemrichmod) 


# do a pairwise comparison with emmeans 
(nemrichmod <- data.frame(emmeans(nemrichmod, specs = pairwise ~ phase)$contrast) |> 
  mutate(group = "Nematodes", .before = 1))

### SHANNON
nemshamod <- glmmTMB(Shannon ~ phase + (1|blokk) + (1|month), 
               data = df, family = gaussian(link = "identity"))
summary(nemshamod) # variance from random effects is very low, check for singularity
check_singularity(nemshamod) # singular fit

nemshamodup <- update(nemshamod, 
                       priors = data.frame(prior = "gamma(1, 2.5)",  
                                           class = "ranef"))
check_singularity(nemshamodup) # no longer singular
simulateResiduals(nemshamodup, plot = TRUE) # looks ok, nothing significant in the qq plot residuals
testDispersion(nemshamodup) # looks good


# do a pairwise comparison with emmeans
(nemshamod <- data.frame(emmeans(nemshamod, specs = pairwise ~ phase)$contrast) |> 
  mutate(group = "Nematodes", .before = 1))


# make boxlots to go with the model results
(df |>
  mutate(
    phase = sub("Pioner", "P", phase),
    phase = sub("Bygg", "B", phase),
    phase = sub("Moden", "M", phase)
  ) |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = Richness,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic(base_size = 12) +
  geom_boxplot(linewidth = 0.6, alpha = 1, outlier.shape = NA, width = 0.25) +
  geom_jitter(
    size = 2, shape = 21, stroke = 1, alpha = 0.5,
    position = position_jitter(height = 0, width = 0.3)
  ) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.text.x = element_text(color = "white"),
    axis.ticks.x = element_blank()
  ) +
  scale_fill_manual(values = c("#F7FBFF", "#9ECAE1", "#08519C")) +
  scale_color_manual(values = rep("black", times = length(unique(nemrar@sam_data$phase)))) +
  ylab(" ") +
  ggtitle("Nematodes") -> nemrich)

(df |>
  mutate(
    phase = sub("Pioner", "P", phase),
    phase = sub("Bygg", "B", phase),
    phase = sub("Moden", "M", phase)
  ) |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = Shannon,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic(base_size = 12) +
  geom_boxplot(linewidth = 0.6, alpha = 1, outlier.shape = NA, width = 0.25) +
  geom_jitter(
    size = 2, shape = 21, stroke = 1, alpha = 0.5,
    position = position_jitter(height = 0, width = 0.3)
  ) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank()
  ) +
  scale_fill_manual(values = c("#F7FBFF", "#9ECAE1", "#08519C")) +
  scale_color_manual(values = rep("black", times = length(unique(nemrar@sam_data$phase)))) +
  ylab(" ") +
  ggtitle(" ") +
  geom_segment(
    x = 1, xend = 2,
    y = 2.2, yend = 2.2
  ) +
  annotate(
    geom = "text", label = "*", size = 12,
    x = 1.5, y = 2.25
  ) +
  geom_segment(
    x = 2, xend = 3,
    y = 2.3, yend = 2.3
  ) +
  annotate(
    geom = "text", label = "***", size = 12,
    x = 2.5, y = 2.35
  ) +
  coord_cartesian(ylim = c(0.8, 2.4)) -> nemsha)

(ggarrange(nemrich, nemsha, nrow = 2) -> nem_alphaplot)

```

fungi

```{r}
# load and normalise phyloseq object:
fungi <- readRDS(here("data/clean_data/heathland-fire-fungi.RDS"))
fungi <- prune_taxa(taxa_sums(fungi) > 0, fungi)

funrar <- rarefy_even_depth(fungi,
  rngseed = 123,
  replace = F,
  trimOTUs = T,
  sample.size = min(sample_sums(fungi))
)

# calculate alpha diversity measures and find medians and IQR:
alpha_stats_fungi <- get_alpha_stats(funrar) |>
    mutate(group = "Fungi", .before = 1)

# test whether differences in alpha diversity are significant between phases:
data.frame(
  estimate_richness(funrar,
    measures = c("Richness", "Shannon")
  ),
  data.frame(funrar@sam_data)
) |> 
  mutate(blokk = sapply(strsplit(Navn, split = '_', fixed = TRUE), `[`, 1)) -> df

### RICHNESS
funrichmod <- glmmTMB(Richness ~ phase + (1|blokk) + (1|month), 
               data = df, family = poisson(link = "log")) # fit model
summary(funrichmod)

simulateResiduals(funrichmod, plot = TRUE) # bad
testDispersion(funrichmod) # looks overdispersed
check_overdispersion(funrichmod) # yep

# re-fit the model with negative binomial distribution
funrichmod <- glmmTMB(Richness ~ phase + (1|blokk) + (1|month), 
               data = df, family = nbinom2(link = "log")) # fit model

summary(funrichmod) # variance from random effects is very low, check for singularity
check_singularity(funrichmod) # model is a singular fit

# the singular fit is likely a symptom of our random "month" effect having few levels. from the output of summary(mod) we see that the random effect of "month" explains <0.000 percent of the variance in the data. to get past this issue, we apply a Gamma prior as recommended in Chung et al. 2013 (https://doi.org/10.1007/s11336-013-9328-2)

funrichmodup <- update(funrichmod, 
                       priors = data.frame(prior = "gamma(1, 2.5)",  
                                           class = "ranef"))
summary(funrichmodup) # looks better
check_singularity(funrichmodup) # no longer singular
testDispersion(funrichmodup) # great
simulateResiduals(funrichmodup, plot = TRUE) # good enough, no significant qq residuals plot


# do a pairwise comparison with emmeans
(funrichmod <- data.frame(emmeans(funrichmodup, specs = pairwise ~ phase)$contrast) |> 
  mutate(group = "Fungi", .before = 1))

### SHANNON
funshamod <- glmmTMB(Shannon ~ phase + (1|blokk) + (1|month), 
               data = df, family = gaussian(link = "identity")) # convergence issues
summary(funshamod) # variance from random effects is very low, check for singularity
check_singularity(funshamod) # model is a singular fit

funshamodup <- update(funshamod, 
                       priors = data.frame(prior = "gamma(1, 2.5)",  
                                           class = "ranef"))
summary(funshamodup)
check_convergence(funshamodup) # now converges
check_singularity(funshamodup) # not singular
testDispersion(funshamodup)
simulateResiduals(funshamodup, plot = TRUE) # looks ok, no significant qq residual plot

# do a pairwise comparison with emmeans
(funshamod <- data.frame(emmeans(funshamodup, specs = pairwise ~ phase)$contrast) |> 
  mutate(group = "Fungi", .before = 1))

(df |>
  mutate(
    phase = sub("Pioner", "P", phase),
    phase = sub("Bygg", "B", phase),
    phase = sub("Moden", "M", phase)
  ) |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = Richness,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic() +
  geom_boxplot(linewidth = 0.6, alpha = 1, outlier.shape = NA, width = 0.5) +
  geom_jitter(
    size = 2, shape = 21, stroke = 1, alpha = 0.5,
    position = position_jitter(height = 0, width = 0.3)
  ) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.text.x = element_text(color = "white"),
    axis.ticks.x = element_blank()
  ) +
  scale_fill_manual(values = c("#DADAEB", "#9E9AC8", "#54278F")) +
  scale_color_manual(values = rep("black", times = length(unique(funrar@sam_data$phase)))) +
  ylab(" ") +
  ggtitle("Fungi") -> funrich)

(df |>
  mutate(
    phase = sub("Pioner", "P", phase),
    phase = sub("Bygg", "B", phase),
    phase = sub("Moden", "M", phase)
  ) |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = Shannon,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic() +
  geom_boxplot(linewidth = 0.6, alpha = 1, outlier.shape = NA, width = 0.5) +
  geom_jitter(
    size = 2, shape = 21, stroke = 1, alpha = 0.5,
    position = position_jitter(height = 0, width = 0.3)
  ) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank()
  ) +
  scale_fill_manual(values = c("#DADAEB", "#9E9AC8", "#54278F")) +
  scale_color_manual(values = rep("black", times = length(unique(funrar@sam_data$phase)))) +
  ylab(" ") +
  ggtitle(" ") +
  geom_segment(
    x = 1, xend = 3,
    y = 4.85, yend = 4.85
  ) +
  annotate(
    geom = "text", label = ".", size = 6,
    x = 2, y = 4.95
  ) +
  geom_segment(
    x = 2, xend = 3,
    y = 4.7, yend = 4.7
  ) +
  annotate(
    geom = "text", label = ".", size = 6,
    x = 2.5, y = 4.8
  ) +
  coord_cartesian(ylim = c(3.8, 5)) -> funsha)

```

bacteria

```{r}
# load and normalise phyloseq object:
bacteria <- readRDS(here("data/clean_data/heathland-fire-bacteria.RDS"))

bacrar <- rarefy_even_depth(bacteria,
  rngseed = 123,
  replace = F,
  trimOTUs = T,
  sample.size = 18963
)

# calculate alpha diversity measures and find medians and IQR:
alpha_stats_bacteria <- get_alpha_stats(bacrar) |>
    mutate(group = "Bacteria", .before = 1)

# test whether differences in alpha diversity are significant between phases:
data.frame(
  estimate_richness(bacrar,
    measures = c("Richness", "Shannon")
  ),
  data.frame(bacrar@sam_data)
) |> 
  mutate(blokk = sapply(strsplit(Navn, split = '_', fixed = TRUE), `[`, 1)) -> df

### RICHNESS
bacrichmod <- glmmTMB(Richness ~ phase + (1|blokk) + (1|month), 
               data = df, family = poisson(link = "log")) # fit model
summary(bacrichmod)

simulateResiduals(bacrichmod, plot = TRUE) # looks ok, no significant qq residuals plot
testDispersion(bacrichmod) # looks good

# do a pairwise comparison with emmeans
(bacrichmod <- data.frame(emmeans(bacrichmod, specs = pairwise ~ phase)$contrast) |> 
  mutate(group = "Bacteria", .before = 1))

### SHANNON
bacshamod <- glmmTMB(Shannon ~ phase + (1|blokk) + (1|month), 
               data = df, family = gaussian(link = "identity")) # convergence problem
summary(bacshamod) # variance from random effects is very low, check for singularity
check_singularity(bacshamod) # model is a singular fit

bacshamodup <- update(bacshamod, 
                       priors = data.frame(prior = "gamma(1, 2.5)",  
                                           class = "ranef"))
summary(bacshamodup) # better
check_singularity(bacshamodup) # the model is no longer a singular fit
check_convergence(bacshamodup) # the model converges
simulateResiduals(bacshamodup, plot = TRUE) # looks good
testDispersion(bacshamodup) # looks good

# do a pairwise comparison with emmeans
(bacshamod <- data.frame(emmeans(bacshamod, specs = pairwise ~ phase)$contrast) |> 
  mutate(group = "Bacteria", .before = 1))

(df |>
  mutate(
    phase = sub("Pioner", "P", phase),
    phase = sub("Bygg", "B", phase),
    phase = sub("Moden", "M", phase)
  ) |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = Richness,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic() +
  geom_boxplot(linewidth = 0.6, alpha = 1, outlier.shape = NA, width = 0.5) +
  geom_jitter(
    size = 2, shape = 21, stroke = 1, alpha = 0.5,
    position = position_jitter(height = 0, width = 0.3)
  ) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank(),
    axis.text.x = element_text(color = "white"),
    axis.ticks.x = element_blank()
  ) +
  scale_fill_manual(values = c("#FEE0D2", "#FC9272", "#CB181D")) +
  scale_color_manual(values = rep("black", times = length(unique(funrar@sam_data$phase)))) +
  ylab(" ") +
  ggtitle("Bacteria") -> bacrich)

(df |>
  mutate(
    phase = sub("Pioner", "P", phase),
    phase = sub("Bygg", "B", phase),
    phase = sub("Moden", "M", phase)
  ) |>
  ggplot(aes(
    x = factor(phase, levels = c("P", "B", "M")),
    y = Shannon,
    fill = factor(phase, levels = c("P", "B", "M")),
    color = factor(phase, levels = c("P", "B", "M"))
  )) +
  theme_classic() +
  geom_boxplot(linewidth = 0.6, alpha = 1, outlier.shape = NA, width = 0.5) +
  geom_jitter(
    size = 2, shape = 21, stroke = 1, alpha = 0.5,
    position = position_jitter(height = 0, width = 0.3)
  ) +
  theme(
    legend.position = "none",
    axis.title.x = element_blank()
  ) +
  scale_fill_manual(values = c("#FEE0D2", "#FC9272", "#CB181D")) +
  scale_color_manual(values = rep("black", times = length(unique(funrar@sam_data$phase)))) +
  ylab(" ") +
  ggtitle("Bacteria") -> bacsha)

```


make supplementary table 1

```{r}
(rbind(
  alpha_stats_plants, 
  alpha_stats_malaise, 
  alpha_stats_pitfall, 
  alpha_stats_nematodes, 
  alpha_stats_fungi, 
  alpha_stats_bacteria
)) -> alpha_stats

writexl::write_xlsx(alpha_stats, "~/Desktop/alpha_stats.xlsx")
```

make supplementary table 2

```{r}
((rbind(
  plantrichmod, 
  pitrichmod, 
  nemrichmod, 
  funrichmod, 
  bacrichmod
)) -> richness_models)
writexl::write_xlsx(richness_models, "~/Desktop/richness_models.xlsx")
```

